[package]
name = "snmp-cat"
version.workspace = true
edition.workspace = true

[dependencies]
ratatui.workspace = true
crossterm.workspace = true
clap.workspace = true
serde.workspace = true
toml.workspace = true
tokio.workspace = true
arboard.workspace = true
mib-parser.workspace = true
snmp-client.workspace = true
